#!/usr/bin/env python3

import sys
from pathlib import Path
import pickle
import os
import re


""" Define location db-file"""
db_location = str(Path.home()) + '/.local/share/template-generator/'
""" Define location of templates """
template_location = str(Path.home()) + '/templates/'

""" Define db-file name """
db_name = 'templates.dat'

""" List of items, to be stored in db-file """
items = []

# TODO: lookup how to store objects in db-file OR create to_string for text-based storage (??How to read??).
class Template:
    """ A class definition for each template, which is stored in db-file."""


    def __init__(self, name: str, arguments):
        self.name = name
        self.arguments = arguments


    def __eq__(self, other):
        """ Override default equality """
        if isinstance(other, Template):
            if other.name != self.name:
                return False
            if len(other.arguments) != len(self.arguments):
                return False
            else:
                for i in range(len(other.arguments)):
                    if other.arguments[i] != self.arguments[i]:
                        return False
            return True
        return False


    def __str__(self):
        output_str = self.name + ": "
        for i in range(len(self.arguments)):
            if len(self.arguments) == i + 1:
                output_str += self.arguments[i]
            else:
                output_str += self.arguments[i] + ", "
        return output_str


def add_item(name: str, arguments):
    if duplicate_template(Template(name, arguments)):
        raise Exception("Template is already in the datafile.")
    else:
        items.append(Template(name, arguments))


def duplicate_template(template):
    for item in items:
        if (item == template):
            return True
    return False


def list_items():
    for item in items:
        print(item)


def print_usage():
    print()
    print("Usage: gen_template <argument>\n"
          "\n"
          "-g   --generate <template> <arguments>       -- Generate a new template.\n"
          "-l   --list                                  -- List all templates.\n"
          "-la  --list-arguments <template>             -- List possible arguments for given template.\n"
          "-o   --output                                -- The output filename, standard out by default.\n"
          "\n"
          "-h   --help                                  -- Display this help message.\n"
          "-v   --version                               -- Display version info.\n"
          "-u   --update                                -- Update template database.\n")


def print_version():
    print(  "gen_template 0.2.1\n"
            "Copyright (C) 2019 Stef Tweepenninckx\n"
    )


def update_database():
    with open('/home/stef/.config/template-generator/config', 'r') as template_list:
        line = template_list.readline().rstrip()
        template_name = re.compile("^\[.+\]$")
        template_end = "end"
        new_template = []
        while line:
            if template_name.match(line) is not None:
                new_template.append(line.replace('[','').replace(']',''))
            elif line == "end":
                if len(new_template) > 1:
                    name = new_template[0]
                    arguments = new_template[1:]
                    try:
                        add_item(name, arguments)
                    except Exception as e:
                        print(e)
                    new_template = []
                elif len(new_template) == 1:
                    try:
                        add_item(new_template[0], [])
                    except Exception as e:
                        print(e)
            else:
                new_template.append(line)
            line = template_list.readline().rstrip()


if __name__ == '__main__':
    try:
        with open(db_location + db_name, 'rb') as f:
            items = pickle.load(f)
    except:
        pass

    if len(sys.argv) <= 1:
        print_usage()
    elif sys.argv[1] == '-h' or sys.argv[1] == '--help':
        print_usage()
    elif sys.argv[1] == '-v' or sys.argv[1] == '--version':
        print_version()
    elif sys.argv[1] == '-g' or sys.argv[1] == '--generate':
        print("TODO: generate")
        # TODO: integrate -o option (check if sys.argv contains -o, cuz len(arguments) can differ)
    elif sys.argv[1] == '-l' or sys.argv[1] == '--list':
        list_items()
    elif sys.argv[1] == '-u' or sys.argv[1] == '--update':
        update_database()
    elif sys.argv[1] == '-a':
        """ added temporary for development purpose, will be removed when finished"""
        add_item(sys.argv[2], sys.argv[3])
    else:
        print_usage()

    with open(db_location + db_name, 'wb') as f:
        pickle.dump(items, f)
